name: docker workflow

on:
  push:

jobs:
  docker_workflow:
    name: docker workflow
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
  
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: dockerhub login
        uses: docker/login-action@v3
        with:
          username: ashour66
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker build and push
        run: |
          docker build -t workflow . 
          docker tag workflow ashour66/workflow:$GITHUB_REF 
          docker push ashour66/workflow:$GITHUB_REF 